language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
install:
  - npm install --no-save --ignore-scripts
before_script:
  - tmp=$(mktemp --directory)
  - bash -O dotglob -O extglob -c 'mv !(node_modules|test.js) "$1"/' bash "$tmp"
  - pack=$(npm pack "$tmp")
  - node -p '"sha512-" + Buffer.from(process.argv[1], "hex").toString("base64")' $(sha512sum -- "$pack")
  - tar --strip-components=1 -x -v -f "$pack"
  - npm install --no-save
